[project]
authors = ["mcgilmore <michael_gilmore@live.com>"]
channels = ["conda-forge"]
name = "codonrs"
platforms = ["osx-arm64", "linux-64", "win-64", "osx-64"]
version = "0.2.6"

[tasks]
build = "cargo build --release && cargo doc --no-deps && cargo readme > README.md"
clean = "cargo clean"
start = "cargo run"
readme = "cargo readme > README.md"

[dependencies]
rust = ">=1.86.0,<1.87"
