[project]
authors = ["mcgilmore <michael_gilmore@live.com>"]
channels = ["conda-forge"]
name = "codonrs"
platforms = ["osx-arm64", "linux-64", "win-64", "osx-64"]
version = "0.2.1"

[tasks]
build = "cargo build --release && cargo doc --no-deps"
clean = "cargo clean"
start = "cargo run"

[dependencies]
rust = ">=1.84.0,<1.85"
